Bump PyVista for new DynamicScraper features
bjlittle/geovista pull request #632
Opened 2024-01-10 02:47 UTC by banesullivan

Resolves #606.

This bumps the version of PyVista and makes some minor changes so that we can leverage PyVista's latest features in its DynamicScraper

2024-01-10 02:52 UTC, banesullivan commented
FYI @bjlittle, I noticed `render_points_as_spheres=True` is used some places here. This may display oddly in the docs as pointed out in https://github.com/MatthewFlamm/pyransame/pull/136#issuecomment-1883499716

2024-01-10 08:03 UTC, bjlittle commented
@banesullivan Lovely! Thanks!

I just need to release `0.4.1` and merge back the changes in the `0.4.x` release feature branch to `main`.

Then you can rebase and we can bank this 🍻

2024-01-10 23:56 UTC, bjlittle requested changes
@banesullivan 

[0.4.1](https://github.com/bjlittle/geovista/releases/tag/v0.4.1) has now been released and the `0.4.x` feature branch has been merged back to `main` (#633).

Fancy rebasing from `main`, then we can bank this :+1:

Thanks!

2024-01-10 23:57 UTC, bjlittle commented on docs/Makefile
> +	@python -m http.server 11000 --directory "$(BUILDDIR)"/html
Nice! :star_struck:

2024-01-11 00:01 UTC, bjlittle commented
> FYI @bjlittle, I noticed `render_points_as_spheres=True` is used some places here. This may display oddly in the docs as pointed out in [MatthewFlamm/pyransame#136 (comment)](https://github.com/MatthewFlamm/pyransame/pull/136#issuecomment-1883499716)

Is this using `vkt.js` under the hood to render? Just curious ...

I noticed that "text" also isn't supported e.g., titles or points labels.

2024-01-11 00:06 UTC, bjlittle commented
@banesullivan @tkoyama010

O--M--G! 😍🚀💯  

I soooo love it! Amazing!
![image](https://github.com/bjlittle/geovista/assets/2051656/22ababe4-0e54-4bee-b1bd-94c10d63cdd7)

2024-01-11 00:12 UTC, bjlittle commented
@banesullivan BTW is there a way to control the size of the `Interactive Scene` rendered window?

2024-01-11 00:14 UTC, tkoyama010 commented
@bjlittle 
Awesome! By the way, the preview of the RTD that you set up at #391 is not showing up in CI, do you know why?

2024-01-11 00:20 UTC, bjlittle commented
> @bjlittle Awesome! By the way, the preview of the RTD that you set up at #391 is not showing up in CI, do you know why?

Yes. I had to temporarily disable it whilst I was working on the `v0.4.x` release feature branch. This is because the `v0.4.x` is based on `geovista` 0.4.0, and this was before the documentation was building successfully (after my recent work on it).

I didn't want failing RTD CI tasks on the `v0.4.x` pull-requests.

I've since enabled it again after deploying `0.4.1`.

2024-01-11 00:22 UTC, bjlittle commented
Yup, that did the trick 👍

2024-01-11 00:24 UTC, tkoyama010 commented
@bjlittle Thanks. WFM.

2024-01-11 00:48 UTC, bjlittle commented
The `pre-commit.ci` job will remain `Pending` until the merge conflict is resolved.

Neat. Didn't realise that `pre-commit.ci` detected this on a pull-request.

![image](https://github.com/bjlittle/geovista/assets/2051656/c80dce3e-601e-4ffb-8f96-2b58de785e22)

2024-01-11 04:23 UTC, banesullivan commented
@bjlittle, the conflict is:

```
<<<<<<< banesullivan/bump-pyvista
  - pyvista >=0.40
=======
  - pyvista >=0.43.1
>>>>>>> main
```

Which do you want to support as the minimum version of PyVista?

2024-01-11 06:05 UTC, bjlittle commented
Go with `>=0.43.1` please.

Thanks 👍

2024-01-11 06:26 UTC, tkoyama010 approved these changes
LGTM

2024-01-11 06:52 UTC, bjlittle approved these changes
Awesome, thanks 🚀

2024-01-11 06:52 UTC, merged

2024-06-29 00:42 UTC, bjlittle commented
@all-contributors please add @banesullivan for infra and examples